/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileProfileNumberRouteImport } from './routes/profile/$profileNumber'
import { Route as AddProfileRouteImport } from './routes/add/profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileProfileNumberRoute = ProfileProfileNumberRouteImport.update({
  id: '/profile/$profileNumber',
  path: '/profile/$profileNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const AddProfileRoute = AddProfileRouteImport.update({
  id: '/add/profile',
  path: '/add/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add/profile': typeof AddProfileRoute
  '/profile/$profileNumber': typeof ProfileProfileNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add/profile': typeof AddProfileRoute
  '/profile/$profileNumber': typeof ProfileProfileNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add/profile': typeof AddProfileRoute
  '/profile/$profileNumber': typeof ProfileProfileNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add/profile' | '/profile/$profileNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add/profile' | '/profile/$profileNumber'
  id: '__root__' | '/' | '/add/profile' | '/profile/$profileNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddProfileRoute: typeof AddProfileRoute
  ProfileProfileNumberRoute: typeof ProfileProfileNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$profileNumber': {
      id: '/profile/$profileNumber'
      path: '/profile/$profileNumber'
      fullPath: '/profile/$profileNumber'
      preLoaderRoute: typeof ProfileProfileNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/profile': {
      id: '/add/profile'
      path: '/add/profile'
      fullPath: '/add/profile'
      preLoaderRoute: typeof AddProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddProfileRoute: AddProfileRoute,
  ProfileProfileNumberRoute: ProfileProfileNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
